# Generated by Django 3.1 on 2020-09-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200824_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fav_recipes',
            field=models.ManyToManyField(blank=True, related_name='fav_recipes', to='recipes.Recipe'),
        ),
    ]
