# Generated by Django 3.1 on 2020-09-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_author_fav_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fav_recipes',
            field=models.ManyToManyField(blank=True, null=True, related_name='fav_recipes', to='recipes.Recipe'),
        ),
    ]
